disabled_rules:
  - trailing_whitespace
  - opening_brace

excluded:
  - Pods
  - SwiftLint/Common/3rdPartyLib
  - "GithubClone/Resources/Generated/R.generated.swift"
  - "Modules/Sources/Authentication/R.generated.swift"
  - "GithubClone/Modules/Sources/NetworkPlatform/Common/HTTPStatusCode.swift"

force_cast: warning

reporter: "xcode"
